import type { FormField } from "@/types/form";
import { AMOUNT_FIELD, NAME_FIELD, ACCOUNTS_FIELD, CATEGORIES_FIELD, PERIOD_FIELD, SORT_FIELD } from "@/constants/fields";

export const INITIAL_BUDGETS_FILTER_FIELDS: FormField[] = [SORT_FIELD, ACCOUNTS_FIELD, CATEGORIES_FIELD, PERIOD_FIELD];

export const INITIAL_BUDGET_FIELDS: FormField[] = [NAME_FIELD, ACCOUNTS_FIELD, CATEGORIES_FIELD, AMOUNT_FIELD, { ...PERIOD_FIELD, required: true }];
