import { ACCOUNT_FIELD, AMOUNT_FIELD, CATEGORY_FIELD, DATE_FIELD, NAME_FIELD, PERIOD_FIELD, SORT_FIELD, ACCOUNTS_FIELD, CATEGORIES_FIELD } from "@/constants/fields";
import type { FormField } from "@/types/form";

export const INITIAL_INCOMES_FILTER_FIELDS: FormField[] = [SORT_FIELD, { ...ACCOUNTS_FIELD, id: "account" }, { ...CATEGORIES_FIELD, id: "category" }, PERIOD_FIELD];

export const INITIAL_INCOME_FIELDS: FormField[] = [NAME_FIELD, ACCOUNT_FIELD, CATEGORY_FIELD, AMOUNT_FIELD, DATE_FIELD];
