import { ACCOUNT_FIELD, ACCOUNTS_FIELD, AMOUNT_FIELD, CATEGORIES_FIELD, CATEGORY_FIELD, DATE_FIELD, DATES_PERIOD_FIELD, NAME_FIELD, SORT_FIELD } from "@/features/default-form";
import type { FilterField } from "@/features/filter";
import type { IncomeItemField } from "../types";

export const INITIAL_INCOMES_FILTER_FIELDS: FilterField[] = [SORT_FIELD, ACCOUNTS_FIELD, CATEGORIES_FIELD, DATES_PERIOD_FIELD];

export const INITIAL_INCOME_FIELDS: IncomeItemField[] = [NAME_FIELD, ACCOUNT_FIELD, CATEGORY_FIELD, AMOUNT_FIELD, DATE_FIELD];
